server:
  port: 7001
spring:
  application:
    name: eurekaServer7001
eureka:
  instance:
    hostname: eureka7001.com
  server:
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false