server:
  port: 7003
spring:
  application:
    name: eurekaServer7003
eureka:
  instance:
    hostname: eureka7003.com
  server:
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false