server:
  port: 8002
spring:
  application:
    name: product8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app.name: 生产者8002
  company.name: 安瑞达科技