server:
  port: 7002
spring:
  application:
    name: eurekaServer7002
eureka:
  instance:
    hostname: eureka7002.com
  server:
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false